'use client';
import { useState, useEffect } from 'react';
import { Heart, Search, ShieldCheck, Users, Sparkles, Check, Globe } from 'lucide-react';
import { Choice } from './choice';
import { Community } from './community-ui';
import { communities } from '@/lib/community';

export default function Matrimony({signedIn}:{signedIn:boolean}) {
 const [mr,setMr]=useState(false); const [gender,setGender]=useState('all'); const [community,setCommunity]=useState('all'); const [profileRequest,setProfileRequest]=useState(0);
 useEffect(()=>{setMr(localStorage.getItem('lingayat-language')==='mr')},[]);
 useEffect(()=>{document.documentElement.lang=mr?'mr':'en'},[mr]);
 function switchLanguage(){localStorage.setItem('lingayat-language',mr?'en':'mr');setMr(!mr)}
 const t=(en:string,ma:string)=>mr?ma:en;
 return <><div className="announcement"><Sparkles size={14}/>{t('A meaningful connection. A membership that’s always free.','अर्थपूर्ण नात्याची सुरुवात. सदस्यत्व नेहमीच मोफत.')}<span>English · मराठी</span></div>
 <header><a className="brand" href="/"><span className="brand-icon"><Heart size={26}/></span><span>Lingayat <b>Shadi</b><small>{t('SHARED VALUES. NEW BEGINNINGS.','समान मूल्ये. नवी सुरुवात.')}</small></span></a><nav><a href="#discover">{t('Find your partner','जोडीदार शोधा')}</a><a href="#how">{t('How it works','हे कसे काम करते')}</a><a href="#community">{t('Our community','आपला समाज')}</a></nav><div className="header-actions"><button className="language" onClick={switchLanguage}><Globe size={16}/>{mr?'English':'मराठी'}</button><button className="btn primary compact" onClick={()=>setProfileRequest(v=>v+1)}>{signedIn?t('My profile','माझे प्रोफाइल'):t('Join for free','मोफत नोंदणी')}</button></div></header>
 <main><section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span/> {t('HINDU LINGAYAT MATRIMONY','हिंदू लिंगायत वधू-वर सूचक')}</p><h1>{t('Rooted in tradition.','परंपरेशी जोडलेले.')}<br/><em>{t('Made for together.','साथ आयुष्यभराची.')}</em></h1><p className="hero-description">{t('Find someone who shares your values, understands your roots, and is ready to write a beautiful new chapter with you.','तुमची मूल्ये जपणारा, तुमच्या परंपरा समजून घेणारा आणि तुमच्यासोबत आयुष्याचा नवा अध्याय सुरू करणारा जोडीदार शोधा.')}</p><div className="hero-checks"><span><Check size={16}/>{t('Every subcommunity welcome','सर्व पोटजातींचे स्वागत')}</span><span><Check size={16}/>{t('No membership fees','कोणतेही सदस्यत्व शुल्क नाही')}</span></div><div className="search-card"><div className="search-title"><Heart size={17}/>{t('Your next chapter starts here','तुमच्या नव्या प्रवासाची सुरुवात इथे')}</div><div className="search-fields"><Choice label={t('I’m looking for','मला शोधायचे आहे')} value={gender} onChange={setGender} items={[["all",t('A life partner','जीवनसाथी')],["woman",t('A bride','वधू')],["man",t('A groom','वर')]]}/><Choice label={t('Subcommunity','पोटजात')} value={community} onChange={setCommunity} items={[["all",t('All subcommunities','सर्व पोटजाती')],...communities.map(([en,ma])=>[en,mr?ma:en] as [string,string])]}/><a className="btn primary search-btn" href="#discover"><Search size={18}/>{t('Find matches','जोडीदार शोधा')}</a></div><p className="search-note"><ShieldCheck size={13}/>{t('Your choice. Your pace. Your new beginning.','तुमची निवड. तुमचा निर्णय. तुमची नवी सुरुवात.')}</p></div></div><div className="hero-visual"><div className="photo-frame"><img src="/wedding-hero.png" alt={t('Illustrative portrait of a joyful South Indian wedding couple','दक्षिण भारतीय वधू-वरांचे प्रातिनिधिक छायाचित्र')} fetchPriority="high"/><span className="photo-label">{t('A lifetime begins with a hello.','एका भेटीतून आयुष्यभराची साथ.')}</span></div><div className="forever-card"><span><Heart size={23}/></span><div><strong>{t('Together, for a lifetime.','साथ, आयुष्यभराची.')}</strong><small>{t('A connection beyond a profile.','प्रोफाइलच्या पलीकडचे नाते.')}</small></div></div><span className="image-note">{t('Illustrative image','प्रातिनिधिक छायाचित्र')}</span></div></section>
 <div className="trust-strip"><div><Heart/><span>{t('100% free membership','१००% मोफत सदस्यत्व')}</span></div><div><Users/><span>{t('All Lingayat subcommunities','सर्व लिंगायत पोटजाती')}</span></div><div><ShieldCheck/><span>{t('Connect at your own pace','तुमच्या सोयीनुसार संवाद')}</span></div><div><Globe/><span>English & मराठी</span></div></div>
 <Community mr={mr} signedIn={signedIn} gender={gender} community={community} profileRequest={profileRequest} onReset={()=>{setGender("all");setCommunity("all")}}/>
 <footer className="wrap"><span>© {new Date().getFullYear()} Lingayat Shadi</span><span>{t('Built around people. Rooted in community.','माणसांना जोडणारे. समाजाशी नाते जपणारे.')}</span></footer></main></>;
}
